language: cpp

compiler:
  - gcc

install:
  - sudo apt-get install libgtest-dev
  
before_script:
  - mkdir build_folder
  - cd build_folder
  - cmake ..
  
script: make

after_success:
  - ./example
  - cd ..
  - rm -rf build_folder/
