language: cpp

compiler:
  - gcc
  
before_script:
  - mkdir build_folder
  - cd build_folder
  - cmake ..
  
script:
  - make
  - ./example
  - ./testing

after_success:
  - cd ..
  - rm -rf build_folder/
