language: cpp

compiler:
  - gcc
  
before_script:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq
  - sudo apt-get install -qq g++-5.2
  - mkdir build_folder
  - cd build_folder
  - cmake ..
  
script:
  - make
  - ./example
  - ./testing

after_success:
  - cd ..
  - rm -rf build_folder/
